name: Test detect breaking changes workflow

on:
  pull_request:
    branches:
      - main

jobs:
  generate-lms-courses-integration-client:
    uses: gsoft-inc/wl-internal-reusable-workflows/.github/workflows/openapi-generate-dotnet-client.yml@main
    with:
      OpenApiSpecPath: 'src\tests\expected-openapi-document.yaml'
      NuGetPackageName: 'Test.CoursesIntegration.Client'
      NuGetPackageVersion: '0.1.0-preview.${{ github.run_number }}'
      ScaffolditTemplateVersion: '1.1.143'
      PublishToFeed: false
    secrets: inherit